<a href="https://colab.research.google.com/github/DeveloperSeJin/-study-machine-learning/blob/main/Chap04_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error as mse
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
file = './drive/MyDrive/CarEx.csv'

In [3]:
Fuel_Efficiency = pd.read_csv(file,  encoding = 'CP949')
Fuel_Efficiency

Unnamed: 0   마력   총중량    연비
0          A  130  1900  16.3
1          B  250  2600  10.2
2          C  190  2200  11.1
3          D  300  2900   7.1
4          E  210  2400  12.1
5          F  220  2300  13.2
6          G  170  2100  14.2

In [4]:
x1= Fuel_Efficiency['마력'].to_numpy()
x2=Fuel_Efficiency['총중량'].to_numpy()
y=Fuel_Efficiency['연비'].to_numpy()

In [5]:
x1 = x1[:, np.newaxis]
x2 = x2[:, np.newaxis]
X = np.c_[np.ones((x1.size, 1)),x1, x2]

In [6]:
X

array([[1.0e+00, 1.3e+02, 1.9e+03],
       [1.0e+00, 2.5e+02, 2.6e+03],
       [1.0e+00, 1.9e+02, 2.2e+03],
       [1.0e+00, 3.0e+02, 2.9e+03],
       [1.0e+00, 2.1e+02, 2.4e+03],
       [1.0e+00, 2.2e+02, 2.3e+03],
       [1.0e+00, 1.7e+02, 2.1e+03]])

In [7]:
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
theta

array([ 3.06040541e+01, -6.89189189e-03, -7.31081081e-03])

In [8]:
y_hat = theta[1] * x1 + theta[2] * x2 + theta[0]
y_hat = np.concatenate(y_hat).tolist()
y_hat = np.array(y_hat)
y_hat

array([15.81756757,  9.87297297, 13.21081081,  7.33513514, 11.61081081,
       12.27297297, 14.07972973])

In [9]:
diff_square = (y_hat - y)**2
e_mse = diff_square.sum() / len(y)
e_mse

0.851949806949806

In [11]:
print("계수 : [", theta[1],theta[2],"]")
print("절편 : ",theta[0])
print("예측 점수 : ", e_mse)

계수 : [ -0.0068918918918915995 -0.007310810810811627 ]
절편 :  30.604054054052725
예측 점수 :  0.851949806949806


In [13]:
print("270 마력 2500kg 자동차의 예상 연비 : ", 270 * theta[1] + 2500 * theta[2] + theta[0])

270 마력 2500kg 자동차의 예상 연비 :  10.466216216212924
